### PR TITLE
added neumann conditions

### PR DESCRIPTION
**Pull request by hverhelst**
small change in kirchhoff example. Neumann assembly was lost.

### CODE REVIEW

**Review by filiatra — APPROVED** [review]

**Comment by hverhelst** [comment]
The previous commit was not (yet) the full fix. Now I added the otangent expression since that was needed (have verified it somewhere else). The `tangent_expr` does exist in `gsExpressions.h`, but that only works for 2D. Would it be nice to combine the 2D and 3D tangent expressions (so `tangent_expr` and `otangent_expr)` to one single expression?

**Comment by filiatra** [comment]
> Would it be nice to combine the 2D and 3D tangent expressions (so `tangent_expr` and `otangent_expr)` to one single expression?

Indeed it would be nice to combine both to a single expression. It is easy to just add an if/else inside the eval(.) of the existing tangent_expr.

**Review by filiatra — CHANGES_REQUESTED** [review]
For the cross product:
gsMatrix<> a(3,1), b(3,1);

a.cross(b) does not work but something like

a.head<3>().cross(b.head<3>())  should do the trick.

**Review by hverhelst — COMMENTED** [review]
Merged the tangent and otangent expressions now. The return type of the eval changed from MatExprType to gsMatrix<Scalar>

**Review by filiatra — APPROVED** [review]

**Pull request merged**
