### PR TITLE
Periodic parametrization of a cylinder-like surface mesh

### PR DESCRIPTION
**Pull request by osmihran**
# Description
This PR generalizes Floater's mesh parametrization algorithm to cylinder-like surfaces. There are two alternative implementations (`gsPeriodicParametrizationOverlap` and `gsPeriodicParametrizationStitch` classes) derived from the standard `gsParametrization` class. While they can both certainly be much improved, I think it can be a good start.

Additionally, there are a few new functions for plotting the parametrizations. Those common to `gsPeriodicParametriztionOverlap` and `gsPeriodicParametrizationStitch` have been implemented in the virtual class `gsPeriodicParametrization`, which is a parent of the former two.

As I've discussed the topic with @filiatra a few weeks ago, I would like him to review, if possible.

# Topics for discussion
- [x] **parametrization_example.cpp** distinguishes between the classes through runtime polymorphism. While I like that one example covers all the three cases, it also looks a bit cumbersome (cf. lines 130 and 136 of the file). Is there a more elegant way?
  **EDIT:** The complexity is now hidden in a separate function.
- [x] Is **parametrization** a good name for the folder in **filedata** to store the inputs for the unittest? We can also put it into **filedata/stl**, although not all of the files are of the **.stl** type.
- [X] Names such as `gsPeriodicParametrizationOverlap` are long and not so nice. Do you have better ideas for naming?
**EDIT:** Remains to decide.
**EDIT:** Decided and committed.
- [x] The unittests could probably be shortened by properly using a `TEST_FIXTURE`; I have experienced some surprising behaviour there (marked with `TODO`), maybe someone can help me improve it.
**EDIT:** fixed with Valgrind.

# The checklist
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
  Yes, see above.
- [x] Have you documented any new codes using Doxygen comments?
  There are loads of comments and even some pictures!
- [x] Have you written new tests or examples for your changes?
  I have modified **parametrization_example.cpp** to cover the two new classes and also added a simple unit test covering the old and new code.
-----

### CODE REVIEW

**Comment by filiatra** [comment]
>     * **parametrization_example.cpp** distinguishes between the classes through runtime polymorphism. While I like that one example covers all the three cases, it also looks a bit cumbersome (cf. lines 130 and 136 of the file). Is there a more elegant way?

I do not see a better way. You could maybe put all the if/else inside a function and just call something like getParamClassPointer(..)
so that the reader is not distructed from all that.

Also: Seems your editor is using TAB for indentation (we use 4 spaces) and there is no indent when starting an "if", could you try to fix indentation?

>     * Is **parametrization** a good name for the folder in **filedata** to store the inputs for the unittest? We can also put it into **filedata/stl**, although not all of the files are of the **.stl** type.

I like the name it is descriptive..

> 
>     * Names such as `gsPeriodicParametrizationOverlap` are long and not so nice. Do you have better ideas for naming?

Indeed they are long.. Ideas:

gsPDParamOverlap (periodic domain parameterization overlap)
gsPDPOverlap

> 
>     * The unittests could probably be shortened by properly using a `TEST_FIXTURE`; I have experienced some surprising behaviour there (marked with `TODO`), maybe someone can help me improve it.

I get failing tests, can you check it out?

Will make a full review later!

**Comment by filiatra** [comment]
In unittests: parametrization/powerplant-mesh2.stl 
file is mentioned but is inexistent...

**Comment by filiatra** [comment]
Also: try valgrind, I think that there are memory issues that lead to strange behaviours that you mention..
For instance:
valgrind ./bin/unittests gsPara
gives some uninitialized values, probably also parametrization_example  in some cases..

**Comment by filiatra** [comment]
Here is also some debug left-overs to be fixed:
/src/gsModeling/gsPeriodicParametrizationOverlap_.cpp:9:21:   required from here
/src/gsModeling/gsPeriodicParametrization.h:106:25: error: ‘class gismo::gsPeriodicParametrization<double>’ has no member named ‘m_valuesV0’
  106 |      GISMO_ASSERT(this->m_valuesV0.rows() == 3, "three rows expected in valuesV0");
      |                   ~~~~~~^~~~~~~~~~
/src/gsCore/gsDebug.h:89:48: note: in definition of macro ‘GISMO_ASSERT’
   89 | #   define GISMO_ASSERT(cond, message) do if(!(cond)) {std::stringstream _m_;\
      |                                                ^~~~
/src/gsModeling/gsPeriodicParametrization.h:107:25: error: ‘class gismo::gsPeriodicParametrization<double>’ has no member named ‘m_valuesV1’
  107 |      GISMO_ASSERT(this->m_valuesV1.rows() == 3, "three rows expected in valuesV1");
      |                   ~~~~~~^~~~~~~~~~
/src/gsCore/gsDebug.h:89:48: note: in definition of macro ‘GISMO_ASSERT’
   89 | #   define GISMO_ASSERT(cond, message) do if(!(cond)) {std::stringstream _m_;\
      |                                                ^~~~
/src/gsModeling/gsPeriodicParametrization.h:109:52: error: ‘class gismo::gsPeriodicParametrization<double>’ has no member named ‘m_valuesV0’
  109 |      GISMO_ASSERT(this->m_paramsV0.cols() == this->m_valuesV0.cols(),
      |                                              ~~~~~~^~~~~~~~~~
/src/gsCore/gsDebug.h:89:48: note: in definition of macro ‘GISMO_ASSERT’
   89 | #   define GISMO_ASSERT(cond, message) do if(!(cond)) {std::stringstream _m_;\
      |                                                ^~~~
/src/gsModeling/gsPeriodicParametrization.h:111:52: error: ‘class gismo::gsPeriodicParametrization<double>’ has no member named ‘m_valuesV1’
  111 |      GISMO_ASSERT(this->m_paramsV1.cols() == this->m_valuesV1.cols(),
      |                                              ~~~~~~^~~~~~~~~~

**Comment by osmihran** [comment]
> > ```
> > * **parametrization_example.cpp** distinguishes between the classes through runtime polymorphism. While I like that one example covers all the three cases, it also looks a bit cumbersome (cf. lines 130 and 136 of the file). Is there a more elegant way?
> > ```
> 
> I do not see a better way. You could maybe put all the if/else inside a function and just call something like getParamClassPointer(..)
> so that the reader is not distructed from all that.

That's a good idea, I tried something of the sort.

> 
> Also: Seems your editor is using TAB for indentation (we use 4 spaces) and there is no indent when starting an "if", could you try to fix indentation?
> 
You are right. The [solution](https://emacs.stackexchange.com/questions/26669/tab-and-spaces-shown-aligned-in-emacs-c-mode-but-not-in-other-editors) might be useful for other emacs users as well: put `(setq-default indent-tabs-mode nil)` into your **.emacs** file to use spaces instead of tabs and compare existing files with `C-x h M-x untabify`.

> > ```
> > * Is **parametrization** a good name for the folder in **filedata** to store the inputs for the unittest? We can also put it into **filedata/stl**, although not all of the files are of the **.stl** type.
> > ```
> 
> I like the name it is descriptive..
> 

Perfect!

> > ```
> > * Names such as `gsPeriodicParametrizationOverlap` are long and not so nice. Do you have better ideas for naming?
> > ```
> 
> Indeed they are long.. Ideas:
> 
> gsPDParamOverlap (periodic domain parameterization overlap)
> gsPDPOverlap
>

That's an interesting idea, although I am not sure, how descriptive "PDP" is. What about:
- gsParametrization
- gsPeriodicParametrization
- gsStitchParametrization
- gsOverlapParametrization
? If that's stitll too long, we can abbreviate "Parametrization" to "Param".

**Comment by osmihran** [comment]
> Here is also some debug left-overs to be fixed:
> /src/gsModeling/gsPeriodicParametrizationOverlap_.cpp:9:21: required from here
> /src/gsModeling/gsPeriodicParametrization.h:106:25: error: ‘class gismo::gsPeriodicParametrization’ has no member named ‘m_valuesV0’
> 106 | GISMO_ASSERT(this->m_valuesV0.rows() == 3, "three rows expected in valuesV0");
> | ~~~~~~^~~~~~~~~~
> /src/gsCore/gsDebug.h:89:48: note: in definition of macro ‘GISMO_ASSERT’
> 89 | # define GISMO_ASSERT(cond, message) do if(!(cond)) {std::stringstream _m_;
> | ^~~~
> /src/gsModeling/gsPeriodicParametrization.h:107:25: error: ‘class gismo::gsPeriodicParametrization’ has no member named ‘m_valuesV1’
> 107 | GISMO_ASSERT(this->m_valuesV1.rows() == 3, "three rows expected in valuesV1");
> | ~~~~~~^~~~~~~~~~
> /src/gsCore/gsDebug.h:89:48: note: in definition of macro ‘GISMO_ASSERT’
> 89 | # define GISMO_ASSERT(cond, message) do if(!(cond)) {std::stringstream _m_;
> | ^~~~
> /src/gsModeling/gsPeriodicParametrization.h:109:52: error: ‘class gismo::gsPeriodicParametrization’ has no member named ‘m_valuesV0’
> 109 | GISMO_ASSERT(this->m_paramsV0.cols() == this->m_valuesV0.cols(),
> | ~~~~~~^~~~~~~~~~
> /src/gsCore/gsDebug.h:89:48: note: in definition of macro ‘GISMO_ASSERT’
> 89 | # define GISMO_ASSERT(cond, message) do if(!(cond)) {std::stringstream _m_;
> | ^~~~
> /src/gsModeling/gsPeriodicParametrization.h:111:52: error: ‘class gismo::gsPeriodicParametrization’ has no member named ‘m_valuesV1’
> 111 | GISMO_ASSERT(this->m_paramsV1.cols() == this->m_valuesV1.cols(),
> | ~~~~~~^~~~~~~~~~

You are right, I was testing in Release only. But it was very strange: at some point I had rows and cols swapped, Release worked fine and Debug failed. In any case, it should be correct now.

**Comment by osmihran** [comment]
> Also: try valgrind, I think that there are memory issues that lead to strange behaviours that you mention..
> For instance:
> valgrind ./bin/unittests gsPara
> gives some uninitialized values, probably also parametrization_example in some cases..

You were right, Valgrind lead me to a explicitly set matrix to zeros before filling them. I thought I filled all the elements but apparently not. This seems to have fixed to strange behaviour of the unittest and it passes on my computer now. Let's see, what the CI will say.
**EDIT**: That seems to have solved the problem!

**Comment by osmihran** [comment]
The test have passed, since then I have made one more commit but it shouldn't break anything.

@filiatra please, let me know once you find time for a review. And we should agree on the names of classes, my suggestion is in the corresponding comment above.

**Comment by osmihran** [comment]
@filiatra I have just committed a suggestion for the renaming of classes. What do you think?

**Comment by osmihran** [comment]
Hi @filiatra,
I have uploaded the change agreed in #448. From my view, we are only a few steps from finishing:
- [x] Class names.
I have committed a suggestion but I am open to a discussion.
- [x] Failing tests:
      The branch used to pass but as far as I can say, even stable now fails. I have had a look into the failed test and it is a complaint that `homebrew-core is a shallow core`. What can I do about it?
- [ ] Your full review:
  Bless it when you have time and are happy with it. (-;

**Comment by osmihran** [comment]
@filiatra , I think we are ready for the big moment. (-:

**Review by filiatra — APPROVED** [review]

**Pull request merged**
