### PR TITLE
Prevent misuses of gsCmdLine

### PR DESCRIPTION
**Pull request by stefantakacs**

### CODE REVIEW

**Comment by stefantakacs** [comment]
Let's see how many tests it breaks...

**Comment by codewerfer** [comment]
Is one of this builds here not a release?

**Comment by stefantakacs** [comment]
I don't know. I am checking locally if there are tests that should be broken.

**Comment by codewerfer** [comment]
OK

**Comment by stefantakacs** [comment]
I do more testing before merging

**Pull request merged**
