### PR TITLE
fix move issues in gsMultiPatch

### PR DESCRIPTION
**Pull request by stefantakacs**

### CODE REVIEW

**Comment by stefantakacs** [comment]
can we merge this?

seems that also in windows it does not create new issues.

**Comment by filiatra** [comment]
There are some rather recent compilers that do not like the "default" keyword.
Better implement the default move constructor and assignment without using the default keyword.

I think the "default" keyword can be used only under the condition
EIGEN_GNUC_AT_MOST(4,7) && !EIGEN_COMP_PGI
but I am not completely sure,

**Comment by stefantakacs** [comment]
okey, then i will change that

**Comment by stefantakacs** [comment]
seems that it works on 3 sites. merging

**Pull request merged**
