### PR TITLE
update remove_ptrs branch

### PR DESCRIPTION
**Pull request by codewerfer**
update remove_ptrs branch to current stable

### CODE REVIEW

**Comment by stefantakacs** [comment]
Its written
"codewerfer wants to merge 9 commits into remove_ptrs from stable".
You want to do the opposite (=merge commets into stable from remove_ptrs")

**Comment by codewerfer** [comment]
No, I want to update remove_ptrs to stable. Direction is correct. But I now make it like it's suggested by github (https://gist.github.com/digitaljhelms/4287848#working-with-a-feature-branch )

**Comment by stefantakacs** [comment]
i see.

you can also do this with a pull request, but it is possible _without_ code review.

alternatively you can use in git something like

git checkout stable
git pull
git checkout remove_ptrs
git merge stable

**Comment by codewerfer** [comment]
Well, after looking deeper into it, what I want was rebase:
```
Assume the following history exists and the current branch is "topic":

                     A---B---C topic
                    /
               D---E---F---G master

       From this point, the result of either of the following commands:

           git rebase master
           git rebase master topic

       would be:

                             A'--B'--C' topic
                            /
               D---E---F---G master
```

**Pull request closed without merging**
