### PR TITLE
fix for https://github.com/gismo/internal/issues/4

### PR DESCRIPTION
**Pull request by codewerfer**
fix for https://github.com/gismo/internal/issues/4

### CODE REVIEW

**Comment by codewerfer** [comment]
I see. Nice..
But, not in `https://github.com/gismo/gismo/blob/stable/src/gsAssembler/gsAssemblerOptions.h` ?

**Comment by stefantakacs** [comment]
I would not put it to gsAssemblerOptions because its only related to this one assembler

**Comment by stefantakacs** [comment]
Can you confirm that the flag is used somewhere and/or confirm that it is passed to gsVisitorCDR ?

I think the class has some issues. The doxygen comments are rather wrong.

**Comment by codewerfer** [comment]
> I would prefer an enum:
> 
> class gsCDRAssembler{
> 
> //...
> enum stabilizationMethod { noStabilization=0, SUPG=1 };
> 
>// ...
> 
> };
> 
> and take only parameters of that type. The gsOptionList is kept as-is.
> 
> That would be consistent with dirichletStrategy and iFaceStrategy.

> I would not put it to gsAssemblerOptions because its only related to this one assembler

OK, but to be consistent, this means also to use the enum in `gsVisitorCDR.h`, and that means an include of `gsCDRAssembler.h`, that includes already `gsVisitorCDR.h`. \
Therefore it makes more sense to add the enum to `gsVisitorCDR.h` instead.

**Pull request merged**
